name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: runtests
        run: |
          julia -e "using InteractiveUtils; versioninfo()"
          julia --color=auto -e "Base.run_main_repl(true, true, false, true, true)"
